---
audiobooks:
  - title: "1% Lifesteal"
    audible: "https://www.audible.com/series/1-Lifesteal-Audiobooks/B0F8QMLV9T"
    amazon: "https://www.amazon.com/dp/B0DGWCJ6JP"
  - title: "A Soldier's Life"
    audible: "https://www.audible.com/series/A-Soldiers-Life-Audiobooks/B0D34549LX"
    amazon: "https://www.amazon.com/dp/B0CW18NDBQ"
  - title: "All the Skills"
    audible: "https://www.audible.com/series/All-the-Skills-Audiobooks/B0BLVJFRKT"
    amazon: "https://www.amazon.com/dp/B0CHXGPPG4"
  - title: "Apocalypse Redux"
    audible: "https://www.audible.com/series/Apocalypse-Redux-Audiobooks/B0BNMHTDC5"
    amazon: "https://www.amazon.com/dp/B0BGMLNT68"
  - title: "Book of the Dead"
    audible: "https://www.audible.com/series/Book-of-the-Dead-Audiobooks/B0CPHQTMHN"
    amazon: "https://www.amazon.com/dp/B0CG9Y4TPK"
  - title: "Defiance of the Fall"
    audible: "https://www.audible.com/series/Defiance-of-the-Fall-Audiobooks/B09B4CQQBT"
    amazon: "https://www.amazon.com/dp/B0916H6FBX"
  - title: "Dungeon Crawler Carl"
    audible: "https://www.audible.com/series/Dungeon-Crawler-Carl-Audiobooks/B0937JMKYV"
    amazon: "https://www.amazon.com/dp/B08BX5D4LC"
  - title: "Eden's Gate"
    audible: "https://www.audible.com/series/Edens-Gate-Audiobooks/B074GFN35N"
    amazon: "https://www.amazon.com/dp/B0753H6GS7"
  - title: "Expeditionary Force"
    audible: "https://www.audible.com/series/Expeditionary-Force-Audiobooks/B01N9CUGHG"
    amazon: "https://www.amazon.com/dp/B07F7T8NPK"
  - title: "Game at Carousel"
    audible: "https://www.audible.com/series/The-Game-at-Carousel-Audiobooks/B0CRV2CFHY"
    amazon: "https://www.amazon.com/dp/B0CLKW91NS"
  - title: "He Who Fights With Monsters"
    audible: "https://www.audible.com/series/He-Who-Fights-with-Monsters-Audiobooks/B08WJ59784"
    amazon: "https://www.amazon.com/dp/B08WF8SB71"
  - title: "Hierarchy"
    audible: "https://www.audible.com/series/Hierarchy-Audiobooks/B0BXWVHLPP"
    amazon: "https://www.amazon.com/dp/B0BJQL8C8V"
  - title: "Mark of the Fool"
    audible: "https://www.audible.com/series/Mark-of-the-Fool-Audiobooks/B0BKHB49TK"
    amazon: "https://www.amazon.com/dp/B0BD696T86"
  - title: "Noobtown"
    audible: "https://www.audible.com/series/Noobtown-Audiobooks/B07WX8HP59"
    amazon: "https://www.amazon.com/dp/B0CHRBL55Y"
  - title: "Past Life Hero"
    audible: "https://www.audible.com/series/Past-Life-Hero-Audiobooks/B0D84BW7WW"
    amazon: "https://www.amazon.com/dp/B0D6D91KYR"
  - title: "Portal to Nova Roma"
    audible: "https://www.audible.com/series/Portal-to-Nova-Roma-Audiobooks/B0BCQP3VTK"
    amazon: "https://www.amazon.com/dp/B09RQXDHCP"
  - title: "Primal Hunter"
    audible: "https://www.audible.com/series/The-Primal-Hunter-Audiobooks/B09MZKWFTB"
    amazon: "https://www.amazon.com/dp/B09MV5TTSM"
  - title: "Reborn: Apocalypse"
    audible: "https://www.audible.com/series/Reborn-Apocalypse-Audiobooks/B07ZWFFH3V"
    amazon: "https://www.amazon.com/dp/B07ZFSQTDQ"
  - title: "Red Rising"
    audible: "https://www.audible.com/series/Red-Rising-Audiobooks/B00U1UJCU8"
    amazon: "https://www.amazon.com/dp/B074BBWZMM"
  - title: "World Sphere"
    audible: "https://www.audible.com/series/World-Sphere-Audiobook/B0DZQMCH45"
    amazon: "https://www.amazon.com/dp/B0F214Q7R6"
---
