name: test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: sudo -n true
