name: test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Run tests with race detection
        run: go test -race ./...

      - name: Check test coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Display coverage
        run: go tool cover -func=coverage.out

  docker:
    runs-on: ubuntu-latest
    needs: go
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ github.repository }}:latest